// Command.h
// Communication protocol
// COPYRIGHT 2012 Sasha Chrichov

#pragma once

enum MRE_ERRORS {
	MRE_ILLEGALCOMMAND = 101,
	MRE_FORMAT = 102,
	MRE_ILLEGALVARIABLE = 103,
	MRE_ILLEGALINDEX = 104,	
	MRE_READONLYVARIABLE = 105,	
	MRE_THREAD = 106,
	MRE_PROGRAMCHECKSUM = 107,
	MRE_PROGRAMMEMORYOVERFLOW = 108,
	MRE_PROGRAMHEADERINVALID = 109,
	MRE_FLASHERASEFAILED = 110,
	MRE_FLASHWRITEFAILED = 111,
	MRE_FLASHLOCKED = 112,
	MRE_FLASHCHECKSUM = 113,
	MRE_ILLEGALFUNCTION = 120,
	MRE_ILLEGALPARAMETERS = 121,
};

//extern struct SendStruct UartSendRequest;

void CommandInit();

class CommChannel;
void ExecuteCommand(uint8_t* com, int comcount, CommChannel* ch);
